on:
  push:
    tags:
      - "*/v*"
      # version tag should be like d1-pac/v1.2.3
  workflow_dispatch:

name: Publish Crate

jobs:
  publish-d1-pac:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/d1-pac')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust targets
        run: rustup target add riscv64imac-unknown-none-elf
      - uses: katyo/publish-crates@v2
        with:
          path: "./d1-pac"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-r528-pac:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/r528-pac')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust targets
        run: rustup target add armv7a-none-eabi
      - uses: katyo/publish-crates@v2
        with:
          path: "./r528-pac"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-xr806-pac:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/xr806-pac')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust targets
        run: rustup target add thumbv8m.main-none-eabi
      - uses: katyo/publish-crates@v2
        with:
          path: "./xr806-pac"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-v853-pac:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v853-pac')
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust targets
        run: rustup target add armv7a-none-eabi
      - uses: katyo/publish-crates@v2
        with:
          path: "./v853-pac"
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
